---
app:
  host: http://localhost:8080

spring:
  devtools:
    add-properties: true
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: jonghoon
    password:
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hse6041@gmail.com
    password: qhsxjdjzqhtquxkw
    properties:
      mail:
        smtp:
          ssl: true
          auth: true
          timeout: 5000
          enable: true
          starttls:
            enable: true

#  level.org.hibernate.sql=DEBUG
#  level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE