---
app:
  host: http://localhost:8080

spring:
  devtools:
    add-properties: true
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username:
    password:
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          ssl: true
          auth: true
          timeout: 5000
          enable: true
          starttls:
            enable: true

server:
  error:
    include-stacktrace: never
